### ISSUE TITLE
Combobox - zindex issue with labels of other controls...

### ISSUE THREAD

**Issue by joelvarty** [agility/agility-plenum-ui#5]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/4520625/156061443-cee08093-da6b-4ab0-b9e4-f072c05e3d87.png">

**Comment by Jerbits** [comment]
fixed : https://github.com/agility/agility-plenum-ui/commit/434c1f9133350da163b7c6518d16e0339e835368
